version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "America/Chicago"
    allow:
      - dependency-name: "discord.py"
        dependency-type: "all"
      - dependency-name: "fluent.runtime"
        dependency-type: "all"
      - dependency-name: "botus_receptus"
        dependency-type: "all"
      - dependency-name: "beautifulsoup4"
        dependency-type: "all"
    open-pull-requests-limit: 10
    assignees:
      - bryanforbes
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "America/Chicago"
    open-pull-requests-limit: 10
    assignees:
      - bryanforbes
