version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "America/Chicago"
    allow:
      - dependency-name: "orjson"
      - dependency-name: "pytz"
    open-pull-requests-limit: 10
    assignees:
      - bryanforbes
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "America/Chicago"
    open-pull-requests-limit: 10
    assignees:
      - bryanforbes
