[tool.poetry]
name = "erasmus"
version = "0.1.1"
description = ""
authors = ["Bryan Forbes <bryan@reigndropsfall.net>"]
license = "BSD-3-Clause"

[tool.poetry.dependencies]
python = "^3.7"
aiodns = "^2.0"
alembic = "^1.0"
beautifulsoup4 = "^4.6"
cchardet = "^2.1"
psycopg2 = "^2.7"
ujson = "^1.35"
"botus_receptus" = {rev = "d9813d3d6e2c1ab4ee77a7413fe930d3599d54ce", git = "https://github.com/bryanforbes/botus_receptus.git", extras = ["gino_typed", "uvloop", "more_itertools"]}
"typing-extensions" = ">=3.7.4"

[tool.poetry.dev-dependencies]
asynctest = "^0.13.0"
black = "^19.3b0"
flake8 = "^3.6"
flake8-bugbear = "^19.3"
flake8-pyi = "^19.3"
mypy = "^0.740"
pre-commit = "^1.12"
pytest = "^5.0"
pytest-asyncio = "^0.10.0"
pytest-cov = "^2.6"
pytest-mock = "^1.10"
pytest-sugar = "^0.9.1"
pytest-vcr = "^1.0.0"
pytest-xdist = "^1.24"

[tool.poetry.scripts]
erasmus = 'erasmus.run:main'

[tool.black]
line-length = 88
target-version = ["py37"]
skip-string-normalization = true
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.pytest_cache
  | \.venv
  | alembic
  | htmlcov
)/
'''

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
