[tool.poetry]
name = "erasmus"
version = "0.1.0"
description = ""
authors = ["Bryan Forbes <bryan@reigndropsfall.net>"]
license = "BSD-3-Clause"

[tool.poetry.dependencies]
python = "^3.7"
aiodns = "^1.1"
alembic = "^1.0"
beautifulsoup4 = "^4.6"
cchardet = "^2.1"
uvloop = "^0.12.0"
psycopg2 = "^2.7"
ujson = "^1.35"
"botus_receptus" = {rev = "6fc82dffe5cc45922db3661e125b168fba86d8f9", git = "https://github.com/bryanforbes/botus_receptus.git", extras = ["gino_typed"]}
pendulum = {git = "https://github.com/bryanforbes/pendulum.git", branch = "update-for-pep-561"}
gino-stubs = {rev = "291b390566416103ce4c88c10521c40344645dea", git = "https://github.com/bryanforbes/gino-stubs.git"}
sqlalchemy-stubs = {rev = "c0d559246eb9ec24a0bf552253ef4018b5f49a31", git = "https://github.com/dropbox/sqlalchemy-stubs.git"}
more_itertools = "^5.0"

[tool.poetry.dev-dependencies]
asynctest = "^0.12.2"
black = "^18.3-alpha.0"
flake8 = "^3.6"
flake8-bugbear = "^18.8"
mypy = "^0.660"
pre-commit = "^1.12"
pytest = "^4.0"
pytest-asyncio = "^0.10.0"
pytest-cov = "^2.6"
pytest-flake8 = "^1.0"
pytest-mock = "^1.10"
pytest-mypy = "^0.3.2"
pytest-sugar = "^0.9.1"
pytest-vcr = "^1.0.0"
pytest-xdist = "^1.24"

[tool.poetry.scripts]
erasmus = 'erasmus.run:main'

[tool.black]
line-length = 88
py36 = true
skip-string-normalization = true
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.pytest_cache
  | \.venv
  | alembic
  | htmlcov
)/
'''

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
