[tool.poetry]
name = "erasmus"
version = "0.1.0"
description = ""
authors = ["Bryan Forbes <bryan@reigndropsfall.net>"]
license = "BSD-3-Clause"

[tool.poetry.dependencies]
python = "^3.7"
aiodns = "^1.1"
alembic = "^1.0"
beautifulsoup4 = "^4.6"
cchardet = "^2.1"
uvloop = "^0.11.3"
psycopg2 = "^2.7"
ujson = "^1.35"
"botus_receptus" = {rev = "54cbfae249ed8cf50858690033fbc59932813bd7", git = "https://github.com/bryanforbes/botus_receptus.git", extras = ["gino"]}

[tool.poetry.dev-dependencies]
asynctest = "^0.12.2"
black = "^18.3-alpha.0"
flake8 = "^3.6"
flake8-bugbear = "^18.8"
mypy = "^0.641.0"
pre-commit = "^1.12"
pytest = "^3.9"
pytest-asyncio = "^0.9.0"
pytest-cov = "^2.6"
pytest-flake8 = "^1.0"
pytest-mock = "^1.10"
pytest-mypy = "^0.3.2"
pytest-vcr = "^0.3.0"
pytest-xdist = "^1.24"
"gino-stubs" = {rev = "7b91ab9e6f4965f1a1199bb1e47f6105299c7774", git = "https://github.com/bryanforbes/gino-stubs.git"}
"sqlalchemy-stubs" = {rev = "8b45fc4345778e3f08e8a3b53ff71aaaa775e632", git = "https://github.com/dropbox/sqlalchemy-stubs.git"}

[tool.poetry.scripts]
erasmus = 'erasmus.run:main'

[tool.black]
line-length = 88
py36 = true
skip-string-normalization = true
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.pytest_cache
  | \.venv
  | alembic
  | htmlcov
)/
'''

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
