name: Unit tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    uses: bryanforbes/python-workflows/.github/workflows/reusable-unit-tests-new.yml@master
    with:
      python_version: '3.12'
      coverage: true
      pytest_args: '--block-network --record-mode=none -p no:sugar'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
